[package]
name = "sam-terminals"
version = "1.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tmux_interface = { version = "0.2.1", features = ["tmux_2_9a"]}
thiserror = "1.0.31"
log = "0.4.16"
